### ISSUE TITLE
version 2.7.0 getNodeById doesn't use idField option...hardcoded to id: 

### ISSUE THREAD

**Issue by benharrell** [500tech/angular2-tree-component#153] opened 2017-01-24 21:28 UTC
TreeModel.prototype.getNodeById = function (id) {
        return this.getNodeBy({ ## _**id: id**_ });
    };

Shouldn't this use _a[this.options.idField] ?

**Comment by adamkleingit** [comment] 2017-02-02 23:30
True. Will be fixed today

**Comment by adamkleingit** [comment] 2017-02-02 23:37
Wait, sorry - that's by design.
TreeNode has a getter for `id` which accesses the idField....

**Closed by adamkleingit** 2017-02-02 23:37 UTC

**Comment by benharrell** [comment] 2017-02-05 16:03
ah thanks i see now...sorry for the wild goose chase!  :)
