### ISSUE TITLE
Error: Cannot read property 'mouse' of undefined

### ISSUE THREAD

**Issue by szepeshazi** [500tech/angular2-tree-component#157] opened 2017-02-02 06:47 UTC
Using angular@2.3.1 and angular2-tree-component@2.7.0, trying the minimalist example shown in the Basic usage section of https://angular2-tree.readme.io/docs, when selecting any node of the tree, I get the following error in Chrome console:
`EXCEPTION: Error in ./TreeNodeComponent class TreeNodeComponent - inline template:15:10 caused by: Cannot read property 'mouse' of undefined`
I tried this in a vanilla installation with angular-cli@1.0.0-beta.26, just added angular2-tree-component to the skeleton. The same works fine with angular-cli@1.0.0-beta.21, which installs angular@2.2.1

Further message in the console:
```
TypeError: Cannot read property 'mouse' of undefined
    at TreeNode.mouseAction (tree-node.model.js:323)
    at View_TreeNodeComponent1.handleEvent_8 (component.ngfactory.js:305)
    at View_TreeNodeComponent1.<anonymous> (view.js:664)
    at HTMLDivElement.<anonymous> (dom_renderer.js:490)
    at ZoneDelegate.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.js:262)
    at ZoneDelegate.invokeTask (zone.js:274)
    at Zone.runTask (zone.js:151)
    at HTMLDivElement.ZoneTask.invoke (zone.js:345)
```

**Comment by adamkleingit** [comment] 2017-02-03 00:35
This sounds very strange. I just released 2.8.0 - can you verify if it still breaks?

**Comment by szepeshazi** [comment] 2017-02-03 09:41
I admit it sounds strange, there should not be any breaking changes between angular 2.2.1 and 2.3.1. The situation is the same with the 2.8.0 version of tree, but I'm getting suspicious that this must be something related to my local environment. I'll try to replicate this with clean virtual machine instances and report back.

**Comment by adamkleingit** [comment] 2017-02-03 11:15
OK, keep me posted. Try removing node_modules and reinstalling again. That voodoo sometimes works....

**Comment by ashkandaie** [comment] 2017-02-15 08:44
Same issue here. Using minimal example as well with new angular-cli project. Using angular 2.4.7

**Comment by girokon** [comment] 2017-02-16 10:00
@adamkleingit Hi, I got the same error. Errors happens in this code: https://github.com/500tech/angular2-tree-component/blob/master/lib/models/tree-node.model.ts#L326 because `this.options.actionMapping` is `undefined`. 
It works for me in minimal exmaple:
```
<Tree [nodes]="nodes" ></Tree>
```

Error in console (lines numbers is worng, incorect source map):
```
EXCEPTION: Error in ./TreeNodeExpanderComponent class TreeNodeExpanderComponent - inline template:1:4 caused by: Cannot read property 'mouse' of undefined

TypeError: Cannot read property 'mouse' of undefined
    at TreeNode.webpackJsonp.1524.TreeNode.mouseAction (tree-node.model.ts:333)
    at View_TreeNodeExpanderComponent1.handleEvent_0 (component.ngfactory.js:66)
    at View_TreeNodeExpanderComponent1.<anonymous> (view.ts:668)
    at HTMLSpanElement.<anonymous> (dom_renderer.ts:518)
    at ZoneDelegate.webpackJsonp.1358.ZoneDelegate.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.ts:241)
    at ZoneDelegate.webpackJsonp.1358.ZoneDelegate.invokeTask (zone.js:274)
    at Zone.webpackJsonp.1358.Zone.runTask (zone.js:151)
    at HTMLSpanElement.ZoneTask.invoke (zone.js:345)
```

Input data:

```
[{
    "id": "58a547c6ecaf2d020cf5719f",
    "name": "Node 1",
    "path": "58a547c6ecaf2d020cf5719f",
    "children": [{
        "id": "58a547c6ecaf2d020cf571a0",
        "name": "Node 2",
        "parent": "58a547c6ecaf2d020cf5719f",
        "path": "58a547c6ecaf2d020cf5719f#58a547c6ecaf2d020cf571a0"
    }, {
        "id": "58a547c6ecaf2d020cf571a1",
        "name": "Node 3",
        "parent": "58a547c6ecaf2d020cf5719f",
        "path": "58a547c6ecaf2d020cf5719f#58a547c6ecaf2d020cf571a1"
    }, {
        "id": "58a547c6ecaf2d020cf571a2",
        "name": "Node 4",
        "parent": "58a547c6ecaf2d020cf5719f",
        "path": "58a547c6ecaf2d020cf5719f#58a547c6ecaf2d020cf571a2",
        "children": [{
            "id": "58a547c6ecaf2d020cf571a3",
            "name": "Node 5",
            "parent": "58a547c6ecaf2d020cf571a2",
            "path": "58a547c6ecaf2d020cf5719f#58a547c6ecaf2d020cf571a2#58a547c6ecaf2d020cf571a3"
        }, {
            "id": "58a547c6ecaf2d020cf571a4",
            "name": "Node 6",
            "parent": "58a547c6ecaf2d020cf571a2",
            "path": "58a547c6ecaf2d020cf5719f#58a547c6ecaf2d020cf571a2#58a547c6ecaf2d020cf571a4"
        }, {
            "id": "58a547c6ecaf2d020cf571a5",
            "name": "Node 7",
            "parent": "58a547c6ecaf2d020cf571a2",
            "path": "58a547c6ecaf2d020cf5719f#58a547c6ecaf2d020cf571a2#58a547c6ecaf2d020cf571a5"
        }]
    }, {
        "id": "58a547c6ecaf2d020cf571a6",
        "name": "Node 8",
        "parent": "58a547c6ecaf2d020cf5719f",
        "path": "58a547c6ecaf2d020cf5719f#58a547c6ecaf2d020cf571a6"
    }]
}]
```

**Comment by girokon** [comment] 2017-02-16 10:09
I tested, if manually pass options, it works without error

**Comment by szepeshazi** [comment] 2017-02-16 12:30
@girokon What do you mean by passing the options manually?

**Comment by girokon** [comment] 2017-02-17 06:43
@szepeshazi I mean this:

```
const actionMapping: IActionMapping = {
    mouse: {
        click: TREE_ACTIONS.TOGGLE_SELECTED,
        dblClick: null,
        contextMenu: null,
        expanderClick: TREE_ACTIONS.TOGGLE_EXPANDED,
        drop: TREE_ACTIONS.MOVE_NODE
    },
    keys: {
        [KEYS.RIGHT]: TREE_ACTIONS.DRILL_DOWN,
        [KEYS.LEFT]: TREE_ACTIONS.DRILL_UP,
        [KEYS.DOWN]: TREE_ACTIONS.NEXT_NODE,
        [KEYS.UP]: TREE_ACTIONS.PREVIOUS_NODE,
        [KEYS.SPACE]: TREE_ACTIONS.TOGGLE_SELECTED,
        [KEYS.ENTER]: TREE_ACTIONS.TOGGLE_SELECTED
    }
};

class MyComponent {

     private treeOptions = {
        actionMapping
    };
}


// in the template:

<Tree [nodes]="nodes" [options]="treeOptions" />

**Comment by szepeshazi** [comment] 2017-02-17 11:05
@girokon Thanks, that fixed the issue for me as well.

**Comment by adamkleingit** [comment] 2017-02-18 14:18
That's strange, there are defaults for the actionMapping and it works for
me.
Can you send a link to a repo or webpackbin where this problem persists?

Thanks

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633


On Fri, Feb 17, 2017 at 1:05 PM, András Szepesházi <notifications@github.com

**Comment by adamkleingit** [comment] 2017-02-22 11:16
@szepeshazi  @girokon I can't reproduce, can you send webpackbin / link to repo?

I'm closing the issue in the meantime

**Closed by adamkleingit** 2017-02-22 11:16 UTC
