### ISSUE TITLE
can anyone help me out regarding the zoneaware issue throwing after installing and configuring your module?

### ISSUE THREAD

**Issue by Muthu2020** [500tech/angular2-tree-component#166] opened 2017-02-09 08:44 UTC
Hi,

Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

In case you are reporting a bug, please specify which version of angular2-tree-component you are using.

Thank you

**Comment by Muthu2020** [comment] 2017-02-09 08:44
angular2-tree-component version - 2.8.0

**Comment by adamkleingit** [comment] 2017-02-09 09:14
Please paste the error, otherwise no one can help you.
Also, please check if this is a duplicate of #160

**Comment by Muthu2020** [comment] 2017-02-09 10:04
This is my error

ZoneAwareError {__zone_symbol__error: Error: (SystemJS) Unexpected token < SyntaxError: Unexpected token < at ZoneDelegate.invoke (h…, __zone_symbol__stack: "(SystemJS) Unexpected token <↵	SyntaxError: Unexpe…p://localhost:3030/dist/build/app/OrbitaModule.js", originalErr: SyntaxError: Unexpected token < at SystemJSLoader.__exec (http://localhost:3030/node_modules/sys…}
__zone_symbol__error
:
Error: (SystemJS) Unexpected token < SyntaxError: Unexpected token < at ZoneDelegate.invoke (http://localhost:3030/node_modules/zone.js/dist/zone.js:242:26) at Zone.run (http://localhost:3030/node_modules/zone.js/dist/zone.js:113:43) at http://localhost:3030/node_modules/zone.js/dist/zone.js:535:57 at ZoneDelegate.invokeTask (http://localhost:3030/node_modules/zone.js/dist/zone.js:275:35) at Zone.runTask (http://localhost:3030/node_modules/zone.js/dist/zone.js:151:47) Evaluating http://localhost:3030/traceur.js Error loading http://localhost:3030/traceur.js Unable to load transpiler to transpile http://localhost:3030/node_modules/angular2-tree-component/dist/angular2-tree-component.js Error loading http://localhost:3030/node_modules/angular2-tree-component/dist/angular2-tree-component.js as "angular2-tree-component" from http://localhost:3030/dist/build/app/OrbitaModule.js at ZoneDelegate.invoke (http://localhost:3030/node_modules/zone.js/dist/zone.js:242:26) at Zone.run (http://localhost:3030/node_modules/zone.js/dist/zone.js:113:43) at http://localhost:3030/node_modules/zone.js/dist/zone.js:535:57 at ZoneDelegate.invokeTask (http://localhost:3030/node_modules/zone.js/dist/zone.js:275:35) at Zone.runTask (http://localhost:3030/node_modules/zone.js/dist/zone.js:151:47) Evaluating http://localhost:3030/traceur.js Error loading http://localhost:3030/traceur.js Unable to load transpiler to transpile http://localhost:3030/node_modules/angular2-tree-component/dist/angular2-tree-component.js Error loading http://localhost:3030/node_modules/angular2-tree-component/dist/angular2-tree-component.js as "angular2-tree-component" from http://localhost:3030/dist/build/app/OrbitaModule.js at new Error (native) at addToError (http://localhost:3030/node_modules/systemjs/dist/system.src.js:122:78) [<root>] at linkSetFailed (http://localhost:3030/node_modules/systemjs/dist/system.src.js:695:21) [<root>] at http://localhost:3030/node_modules/systemjs/dist/system.src.js:495:9 [<root>] at Zone.run (http://localhost:3030/node_modules/zone.js/dist/zone.js:113:43) [<root> => <root>] at http://localhost:3030/node_modules/zone.js/dist/zone.js:535:57 [<root>] at Zone.runTask (http://localhost:3030/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>] at drainMicroTaskQueue (http://localhost:3030/node_modules/zone.js/dist/zone.js:433:35) [<root>] at XMLHttpRequest.ZoneTask.invoke (http://localhost:3030/node_modules/zone.js/dist/zone.js:349:25) [<root>]
__zone_symbol__stack
:
"(SystemJS) Unexpected token <↵	SyntaxError: Unexpected token <↵	    at ZoneDelegate.invoke (http://localhost:3030/node_modules/zone.js/dist/zone.js:242:26)↵

**Comment by adamkleingit** [comment] 2017-02-13 09:12
Can you paste your systemJS config file and package.json? No one can really help you if you don't supply data....

**Comment by adamkleingit** [comment] 2017-02-22 11:15
Hey, @Muthu2020, please use the updated docs for using SystemJS (see the readme).
Thanks

**Closed by adamkleingit** 2017-02-22 11:15 UTC
