### ISSUE TITLE
New Requirement: Store expanded state in cookie

### ISSUE THREAD

**Issue by johnny2002** [500tech/angular2-tree-component#161] opened 2017-02-04 03:02 UTC
Please add a new feature to store tree node expanded/collapsed state in cookie, like jquery-tree does.

**Comment by denkomanceski** [comment] 2017-02-05 20:36
I dont think the way this issue is written is okay. You write it like a task to some developer that works for you and that is not how open source works. You should maybe ask: 'Could someone elaborate on how can we implement a cookie based store' or 'is something like that planned or possible'.

**Comment by adamkleingit** [comment] 2017-02-09 09:21
@denkomanceski is right.
Also, this is duplicate of #111 - closing

**Closed by adamkleingit** 2017-02-09 09:21 UTC
