### ISSUE TITLE
Error in npm compile

### ISSUE THREAD

**Issue by johnny2002** [500tech/angular2-tree-component#163] opened 2017-02-07 09:31 UTC
I often got below error when running "npm start":

node_modules/angular2-tree-component/dist/models/tree-node.model.d.ts(17,17): error TS7006: Parameter 'any' implicitly has an 'any' type.

Temp solution for me is to comment out the following line in tree-node.model.d.ts:
    children: TreeNode[];
    //allowDrop: (any) => boolean;
    private _originalNode;
    readonly originalNode: any;

**Comment by johnny2002** [comment] 2017-02-07 11:12
another temp solution:
change the line
 allowDrop: (any) => boolean;  
to
  allowDrop: (any: any) => boolean;

**Comment by adamkleingit** [comment] 2017-02-09 09:19
duplicate of #159

**Closed by adamkleingit** 2017-02-09 09:19 UTC
