### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by paulsmith-ru** [500tech/angular2-tree-component#146] opened 2017-01-13 11:34 UTC
today I got an error
```
node_modules/angular2-tree-component/dist/models/tree-node.model.d.ts(1,1): erro
r TS2688: Cannot find type definition file for 'core-js'.
```
in the file "tree-node.model.d.ts" I saw three slash
`/// <reference types="core-js" />`

**Comment by PrimeByDesign** [comment] 2017-01-13 15:43
Same for me!

**Comment by adamkleingit** [comment] 2017-02-02 21:02
Hey,
This is duplicate of #139 - closing this one. Thanks

**Closed by adamkleingit** 2017-02-02 21:02 UTC
